### ISSUE TITLE
feature request: 通知栏增强

### ISSUE THREAD

**Issue by ericclose** [972091604/bujuan-sixbugs#1]
开发大大，不知道此前有没有人提过 **适配 Android 10 通知栏** 调节音乐播放进度的请求呢😁，如图：

![Screenshot_20200430-184601_Lawnchair](https://user-images.githubusercontent.com/34526560/80701956-e5ed6a00-8aa5-11ea-84cc-3641db7488d3.png)

**Comment by 2697a** [comment]
嗯，我觉得可以提上日程了
