### ISSUE TITLE
横屏适配

### ISSUE THREAD

**Issue by FrzMtrsprt** [972091604/bujuan-sixbugs#2]
播放页在横屏状态下无法显示完整，且屏幕方向不同于应用启动时的方向时，设置页面的髙度不会跟随变化…于是设置页面可能无法显示完全

**Comment by 2697a** [comment]
好的，我尽快做一下适配

**Comment by lhzmrl** [comment]
> 播放页在横屏状态下无法显示完整，且屏幕方向不同于应用启动时的方向时，设置页面的髙度不会跟随变化…于是设置页面可能无法显示完全

一个音乐软件要啥横屏呀，把竖屏锁死完事。

**Comment by FrzMtrsprt** [comment]
> > 播放页在横屏状态下无法显示完整，且屏幕方向不同于应用启动时的方向时，设置页面的髙度不会跟随变化…于是设置页面可能无法显示完全
> 
> 一个音乐软件要啥横屏呀，把竖屏锁死完事。

给平板和机顶盒用啊

**Comment by lhzmrl** [comment]
> > > 播放页在横屏状态下无法显示完整，且屏幕方向不同于应用启动时的方向时，设置页面的髙度不会跟随变化…于是设置页面可能无法显示完全
> > 
> > 
> > 一个音乐软件要啥横屏呀，把竖屏锁死完事。
> 
> 给平板和机顶盒用啊

付出和收益不成比。除了少数几个大的视频软件，基本没有厂家适应横屏了。随着手机屏幕越来越大，平板更侧重于生产力工具，现在还在出的也就华为和苹果。至于机顶盒，机顶盒上看这个的更少了。当然作者有时间可以做的。
